import 'package:isar_community/isar.dart';
import 'collections.dart';

/// Central registry of all Isar collection schemas for Phase 5 offline support.
///
/// Pass [allSchemas] to [LocalDatabaseService.initialize()] to open Isar
/// with all collections.
abstract final class DatabaseCollections {
  /// Every collection schema used by the app.
  ///
  /// Generated by isar_generator from the @collection annotated classes.
  /// To regenerate, run:
  ///   dart run build_runner build --delete-conflicting-outputs
  static List<CollectionSchema> get allSchemas => [
        PatientCollectionSchema,
        AlertCollectionSchema,
        DeviceCollectionSchema,
        HospitalCollectionSchema,
        SensorReadingCollectionSchema,
        UserCollectionSchema,
      ];

  static const int schemaVersion = 1;

  /// Schema migration logic.
  ///
  /// Invoked by Isar when [schemaVersion] changes.
  static Future<void> onMigration(
    Isar isar,
    int currentVersion,
    int targetVersion,
  ) async {
    if (currentVersion < 1) {
      await _migrateV0ToV1(isar);
    }
  }

  static Future<void> _migrateV0ToV1(Isar isar) async {
    // Initial schema — no data migrations needed yet.
    // Future versions should handle field additions/renames here.
  }
}
