// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Z78N69LiMg92G5t9YJNxOl_zspEdISI',
    appId: '1:85904350158:web:aa0bc520d3de6fa49c699f',
    messagingSenderId: '85904350158',
    projectId: 'neurobleed-alert',
    authDomain: 'neurobleed-alert.firebaseapp.com',
    storageBucket: 'neurobleed-alert.firebasestorage.app',
    measurementId: 'G-V9JV134ZL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu6vcbGdJcXeTZ-9dYAUZ6ZRotTDlQ4LY',
    appId: '1:85904350158:android:eeba64ee389dd4719c699f',
    messagingSenderId: '85904350158',
    projectId: 'neurobleed-alert',
    storageBucket: 'neurobleed-alert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbNgSRRAoJeOldxCVZb_zT05X51Ep7fAc',
    appId: '1:85904350158:ios:636b27d1a4c11ddc9c699f',
    messagingSenderId: '85904350158',
    projectId: 'neurobleed-alert',
    storageBucket: 'neurobleed-alert.firebasestorage.app',
    iosBundleId: 'com.example.neurobleedMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1Z78N69LiMg92G5t9YJNxOl_zspEdISI',
    appId: '1:85904350158:web:90dbc8e63d5e76c49c699f',
    messagingSenderId: '85904350158',
    projectId: 'neurobleed-alert',
    authDomain: 'neurobleed-alert.firebaseapp.com',
    storageBucket: 'neurobleed-alert.firebasestorage.app',
    measurementId: 'G-DN5Z1175DD',
  );
}
